<?php
    session_start();
?>
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!--Navigation Bar-->
        <!-- Load an icon library to show a hamburger menu (bars) on small screens -->
        <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <!-- Navigation Bar style sheet -->
        <link type="text/css" rel="stylesheet" href="../CSS/navigationbar.css">

        <!-- JQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>


        <!-- Side Bar style sheet  
        <link type="text/css" rel="stylesheet" href="style.css">
        -->

        <style>
            /* The side navigation menu */
            .sidebar {
              margin: 0;
              padding: 0;
              width: 200px;
              background-color: #f1f1f1;
              position: fixed;
              height: 100%;
              overflow: auto;
            }
            
            /* Sidebar links */
            .sidebar a {
              display: block;
              color: black;
              padding: 16px;
              text-decoration: none;
            }
            
            /* Active/current link */
            .sidebar a.active {
              background-color: #04AA6D;
              color: white;
            }
            
            /* Links on mouse-over */
            .sidebar a:hover:not(.active) {
              background-color: #555;
              color: white;
            }
            
            /* Page content. The value of the margin-left property should match the value of the sidebar's width property */
            div.main {
              margin-left: 200px;
              padding: 1px 16px;
              height: 1000px;
            }
            
            /* On screens that are less than 700px wide, make the sidebar into a topbar */
            @media screen and (max-width: 700px) {
              .sidebar {
                width: 100%;
                height: auto;
                position: relative;
              }
              .sidebar a {float: left;}
              div.content {margin-left: 0;}
            }
            
            /* On screens that are less than 400px, display the bar vertically, instead of horizontally */
            @media screen and (max-width: 400px) {
              .sidebar a {
                text-align: center;
                float: none;
              }
            } 
        </style>

        <!-- Vertical bar handler 
        <script type="text/javascript" src="verticalbar.js"></script> 
        -->
        <title>User View</title>

    </head>
    <body>
        <div class="topnav" id="myTopnav">
            <a href="../index.html"><i class="fa fa-home"></i> Inicio</a>
            <a href="#contact"><i class="fa fa-fw fa-envelope"></i> Contacto</a>
            <a href="#about">Acerca de</a>
            <a class="active" href="#login"><i class="fa fa-user-circle-o"></i> 
                <?php
                    echo $_SESSION["User"];
                ?>
            </a>

            <!--The link with class="icon" is used to open and close the topnav on small screens.-->
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">
                <i class="fa fa-bars"></i>
            </a>

            <script>
            /* Toggle between adding and removing the "responsive" class to topnav when the user clicks on the icon */
            function myFunction() {
                var x = document.getElementById("myTopnav");
                if (x.className === "topnav") {
                    x.className += " responsive";
                } else {
                    x.className = "topnav";
                }
            }
            </script>
        </div> 

        <div class="sidebar" id="sidebar">
            <!-- Autogenerated with js file -->
        </div>

        <script>
            function getUserDevices(username)
            {
                console.log("sending " + username);
                var oReq = new XMLHttpRequest(); // New request object
                
                oReq.onload = function() {
                    // This is where you handle what to do with the response.
                    // The actual data is found on this.responseText
                    
                    var ans = this.responseText;

                    console.log("response " + ans);

                    const obj = JSON.parse(ans);

                    var vsidebar = $("#sidebar");

                    var sdbarCode = "";
                    
                    for (const x in obj)
                    {
                        if (obj[x] != 0)
                        {
                            sdbarCode += `<a href="#nothing">` + x + " (" + obj[x] + ")</a>";
                        }
                        console.log(x + "," + obj[x]);
                    }

                    vsidebar.html(vsidebar.html() + sdbarCode);
                };
                oReq.open("GET", "userdevices.php?user=" + username, true);
                //                               ^ Don't block the rest of the execution.
                //                                 Don't wait until the request finishes to
                //                                 continue.
                oReq.send();
            }
            function createSideBar()
            {
                var vsidebar = $("#sidebar");

                var sdbarCode = `
                                <a class="active" href="#home">Home</a>
                                <p style="text-align:center; font-weight:bold;">Mis dispositivos</p>
                                <hr>
                                `;
                vsidebar.html(sdbarCode);
            }

            var user = "<?php echo $_SESSION['User']; ?>";
            createSideBar();
            getUserDevices(user);
            
        </script>

        <div class="main">
            <h1>Panel principal</h1>
            <p>
                <?php
                    echo "Bienvenido " . $_SESSION["User"];
                ?>
            </p>
        </div>

    </body>
</html>