<?php
    session_start();
?>
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!--Navigation Bar-->
        <!-- Load an icon library to show a hamburger menu (bars) on small screens -->
        <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <!-- Navigation Bar style sheet -->
        <link type="text/css" rel="stylesheet" href="../CSS/navigationbar.css">

        <!-- JQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

        <!-- Side Bar style sheet -->
        <link type="text/css" rel="stylesheet" href="style.css">

        <title>User View</title>

    </head>
    <body>
        <div class="topnav" id="myTopnav">
            <a href="../index.html"><i class="fa fa-home"></i> Inicio</a>
            <a href="#contact"><i class="fa fa-fw fa-envelope"></i> Contacto</a>
            <a href="#about">Acerca de</a>
            <a class="active" href="#login"><i class="fa fa-user-circle-o"></i> 
                <?php
                    echo $_SESSION["User"];
                ?>
            </a>

            <!--The link with class="icon" is used to open and close the topnav on small screens.-->
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">
                <i class="fa fa-bars"></i>
            </a>

            <script>
            /* Toggle between adding and removing the "responsive" class to topnav when the user clicks on the icon */
            function myFunction() {
                var x = document.getElementById("myTopnav");
                if (x.className === "topnav") {
                    x.className += " responsive";
                } else {
                    x.className = "topnav";
                }
            }
            </script>
        </div> 

        <div class="sidebar" id="sidebar">
            <!-- Autogenerated with js file -->
        </div>

        <div class="main">
            <h1>Panel principal</h1>
            <p>
                <?php
                    echo "Bienvenido " . $_SESSION["User"];
                ?>
            </p>
        </div>

        <!-- Generate widgets -->
        <!-- Vertical bar handler -->
        <script type="text/javascript" src="verticalbar.js"></script>
        
        <script>
            var user = "<?php echo $_SESSION['User']; ?>";
            
            createSideBar();
            getUserDevices(user);
        </script>

    </body>
</html>